### ISSUE TITLE
Post Admin MVP Neatness

### ISSUE THREAD

**Issue by cooperj** [SoCSTech/asgard#36]
# Tasks
 - [ ] Make the file `admin/src/components/timetables/timetablePage.tsx` less long and break the bits up
- [ ] Reorganise the components folders so that there its like a big `utils` folder (this doesnt include shadcn ui stuff)
- [ ] Replace the browser based `confirm` thing so it feels more like an app and not a 90s website [shadcn alert?](https://ui.shadcn.com/docs/components/alert-dialog)
- [ ] Improve the action buttons widget thing, make it a proper component and make it work better on mobile
- [ ] Hex Colours to SoCS Names component (for things like the Default Event Colour label)
- [ ] Tidy up the timetables info page so that data looks better on desktop and awesome on mobile
- [ ] Add some juicy animations rather than fading
- [ ] Only show the timetables that can be added to groups and not just all the timetables
- [ ] Create a logo for asgard, or brand the application in the university logo for stuff like the favicon (but need to take special care that the logo doesnt conflict with the brand of [The UniLincoln App](https://app.lincoln.ac.uk)

# Current State
![Image](https://github.com/user-attachments/assets/559ea721-91cd-43a0-b43c-3b4d76a7921a)
![Image](https://github.com/user-attachments/assets/772924e1-2bb1-4489-a15e-0f11a566cef7)
