### ISSUE TITLE
Support for events being moved or cancelled

### ISSUE THREAD

**Issue by cooperj** [SoCSTech/asgard#39]
### Add support in Y2 and Asgard to allow for events to be moved or cancelled.

This would allow for very easy and quick communication of events being moved to different spaces or if they have been cancelled, allowing students to be informed quickly.

This should be used very sparingly and only in cases where we would typically put a paper sign on the door.

#### States

If an event is **cancelled**, it should be shown on the screen as being cancelled... but it should still count the room as being empty.

If the event is **moved**, it should say it has been moved and give the user a space code for where the session will now be taking place.

If the event is in a **normal** state, it should act as normal.

#### To-do this:

- [ ] Add a field to the event schema that has a message/new space code.
- [ ] Add an enum with the options of `[ 'normal', 'moved', 'cancelled']`
- [ ] Add the enum back to the event, default to a new space.
- [ ] Add the logic to…
- - [ ] Asgard admin
- - [ ] Yggdrasil2
- [ ] ensure jobs/timetable-importer doesn't get affected/all events from timetable are normal.
